#!/bin/bash
source $HOME/.config/colors/current
if [ -e /usr/bin/nvidia-smi ]; then
    temp1=$(nvidia-smi -q -d TEMPERATURE -i 0 | awk '/GPU Current Temp/ {print $5}')
    temp2=$(nvidia-smi -q -d TEMPERATURE -i 1 | awk '/GPU Current Temp/ {print $5}')
else
    temp1=$(sensors | grep GPU | awk '{print $2}' | sed 's/[+,°,C]//g')
fi
if [ $temp1 -gt 52 ]; then
    echo "<span color='$color11'>$temp1°C</span>"
elif [ $temp1 -gt 75 ]; then
    echo "<span color='$color9'>$temp1°C</span>"
else
    echo "<span color='$color10'>$temp1°C</span>"
fi
