#!/bin/bash
drives=($(lsblk -d | awk {'print $1'} | sed '1d' | head -n -1))
count="$(lsblk -d | awk {'print $1'} | sed '1d' | head -n -1 | wc -l)"

for (( run=1; run<=count; run++ ))
do
        read hdd$run
        sudo hddtemp -q /dev/${drives[$run - 1]} | awk {'print $NF'} | grep "°C"

done
echo "$hdd1"
echo "$hdd2"
echo "$hdd3"

#sudo hddtemp /dev/sdb | awk {'print $3'}
