#!/bin/bash
lat=$(ping -c 3 8.8.8.8 | tail -1 | awk '{print $4}' | cut -d '/' -f 2 | cut -d '.' -f 1)
if [[ -z "$lat" ]]; then
        echo "<span color='#b84131'>No Connection</span>"
elif [ $lat -gt '50' ]; then
        echo "<span color='#c4a500'>$lat ms</span>"
elif [ $lat -gt '150' ]; then
        echo "<span color='#b84131'>$lat ms</span>"
else
        echo "<span color='#7da900'>$lat ms</span>"
fi
