#!/usr/bin/env bash
#
# Pulseaudio volume control using ponymix, designed to be used with
# i3blocks (https://github.com/vivien/i3blocks/).
#
# Copyright (C) 2015  Tomasz Kramkowski <tk@the-tk.com>
#
# This program is free software. It is licensed under version 3 of the
# GNU General Public License.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see [http://www.gnu.org/licenses/].
#
# BLOCK_INSTANCE is passed in the format <max-volume>#<step>
# <max-volume> is passed with --max-volume and <step> is used as the
# volume increase/decrease step.
#
# Right Click toggles mute, Scroll Up increases volume, and Scroll Down
# decreases volume.

CEILING="${BLOCK_INSTANCE%/*}"
CEILING="${CEILING:-100}"

STEP="${BLOCK_INSTANCE#*/}"
STEP="${STEP:-5}"

case $BLOCK_BUTTON in	# Ponymix auto-prints volume so >/dev/null
  1) pavucontrol &>/dev/null;;
  3) ponymix toggle >/dev/null;;				# Right Click
  4) ponymix --max-volume $CEILING increase $STEP >/dev/null;;	# Scroll Up
  5) ponymix --max-volume $CEILING decrease $STEP >/dev/null;;	# Scroll Down
esac

VOLUME="$(ponymix get-volume)"

if ponymix is-muted; then
    STATE="<span color='#707070'> </span><span color='#ed5466'> MUTED</span>"
elif [ $VOLUME -ge '80' ]; then
    STATE="<span color='#707070'> </span><span color='#050505'> $VOLUME</span>"
elif [ $VOLUME -ge '50' ]; then
    STATE="<span color='#707070'> </span><span color='#5e5e5e'> $VOLUME</span>"
elif [ $VOLUME -gt '33' ]; then
    STATE="<span color='#707070'> </span><span color='#8a8a8a'> $VOLUME</span>"
 elif [ $VOLUME == '0' ]; then
    STATE="<span color='#707070'> </span><span color='#b6b6b6'> $VOLUME</span>"
else
	STATE="<span color='#707070'> </span><span color='#b6b6b6'> $VOLUME</span>"
fi

echo "$STATE"	# full_text
echo "$STATE"	# short_text
