#!/usr/bin/env bash
msg(){
    echo "$(tput bold)$(tput setaf 4)>>$(tput sgr0) ${@}"
}

err(){
    echo "$(tput bold)$(tput setaf 1)!!$(tput sgr0) ${@}"
}

ask() {
  # http://djm.me/ask
  while true; do

    if [ "${2:-}" = "Y" ]; then
      prompt="Y/n"
      default=Y
    elif [ "${2:-}" = "N" ]; then
      prompt="y/N"
      default=N
    else
      prompt="y/n"
      default=
    fi

    # Ask the question
    read -p "$(tput bold)$(tput setaf 3)?$(tput sgr0) $1 ($prompt): " REPLY

    # Default?
    if [ -z "$REPLY" ]; then
       REPLY=$default
    fi

    # Check if the reply is valid
    case "$REPLY" in
      Y*|y*) return 0 ;;
      N*|n*) return 1 ;;
    esac

  done
}
